/*
    파일명 : 02_SAEROI_drop_v9_final.sql
    목적   : v9 최종 DB 객체 전체 삭제. DBeaver/JDBC 실행용. 테이블이 없어도 계속 실행되도록 작성. SQL*Plus / 구분자는 사용하지 않는다.
*/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE attached_file CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE board_comment CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE defect_action CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE defect_list CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE inspection CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE product_inout CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE material_inout CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE production CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE equipment_history CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE actual_cost_daily CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE equipment_maintenance CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE equipment_trouble CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE process_detail CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE process CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE bom_detail CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE bom CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE work_order CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE production_plan CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE inventory CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE standard_cost CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE defect CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE equipment CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE board CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE notice CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE item CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE emp CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE line CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE client CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE equipment_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE equipment_history_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_material_inout';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_inventory_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;

PURGE RECYCLEBIN;
